web/router.ex
defmodule PhoenixCart.Router do
  use PhoenixCart.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixCart do
    pipe_through :browser # Use the default browser stack

    resources "/categories", CategoryController
    resources "/products", ProductController
    resources "/orders", OrderController
    resources "/cart", CartController, only: [:index, :update, :delete]
    resources "/checkout", CheckoutController, only: [:update, :index]

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixCart do
  #   pipe_through :api
  # end
end

web/models/category.ex
defmodule PhoenixCart.Category do
  use PhoenixCart.Web, :model

  schema "categories" do
    field :name, :string
    has_many :products, PhoenixCart.Product

    timestamps
  end

  @required_fields ~w(name)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/category_controller.ex
defmodule PhoenixCart.CategoryController do
  use PhoenixCart.Web, :controller

  alias PhoenixCart.Category

  plug :scrub_params, "category" when action in [:create, :update]
  plug PhoenixCart.Plugs.Cart when action in [:index, :show]

  def index(conn, _params) do
    categories = Repo.all(Category)
    render(conn, "index.html", categories: categories)
  end

  def new(conn, _params) do
    changeset = Category.changeset(%Category{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"category" => category_params}) do
    changeset = Category.changeset(%Category{}, category_params)

    if changeset.valid? do
      Repo.insert!(changeset)

      conn
      |> put_flash(:info, "Category created successfully.")
      |> redirect(to: category_path(conn, :index))
    else
      render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    [category] = Repo.all(from(p in Category, where: p.id == ^id, preload: :products))
    render(conn, "show.html", category: category)
  end

  def edit(conn, %{"id" => id}) do
    category = Repo.get!(Category, id)
    changeset = Category.changeset(category)
    render(conn, "edit.html", category: category, changeset: changeset)
  end

  def update(conn, %{"id" => id, "category" => category_params}) do
    category = Repo.get!(Category, id)
    changeset = Category.changeset(category, category_params)

    if changeset.valid? do
      Repo.update!(changeset)

      conn
      |> put_flash(:info, "Category updated successfully.")
      |> redirect(to: category_path(conn, :index))
    else
      render(conn, "edit.html", category: category, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    category = Repo.get!(Category, id)
    Repo.delete!(category)

    conn
    |> put_flash(:info, "Category deleted successfully.")
    |> redirect(to: category_path(conn, :index))
  end

end

web/views/category_view.ex
defmodule PhoenixCart.CategoryView do
  use PhoenixCart.Web, :view
end

web/templates/category/edit.html.eex
<h2>Edit category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :update, @category) %>

<%= link "Back", to: category_path(@conn, :index) %>

web/templates/category/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, "Name" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/category/index.html.eex
<h2>Listing categories</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for category <- @categories do %>
    <tr>
      <td><%= category.name %></td>

      <td class="text-right">
        <%= link "Show", to: category_path(@conn, :show, category), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: category_path(@conn, :edit, category), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: category_path(@conn, :delete, category), method: :delete, class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New category", to: category_path(@conn, :new) %>

web/templates/category/new.html.eex
<h2>New category</h2>

<%= render "form.html", changeset: @changeset,
                        action: category_path(@conn, :create) %>

<%= link "Back", to: category_path(@conn, :index) %>

web/templates/category/show.html.eex
<h2><%= @category.name %></h2>

<ul>
<%= for product <- @category.products do %>
    <li><%= link product.name, to: product_path(@conn, :show, product) %> $<%= product.price %></li>
<% end %>
</ul>

<%= link "Back", to: category_path(@conn, :index) %>